apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-mysql-pv
  labels:
    app: mysql
    store: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Release.Namespace }}-local-storage
  hostPath:
    path: /mnt/data/{{ .Release.Namespace }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane
