apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: "400m"
    limits.cpu: "1200m"
    requests.memory: "768Mi"
    limits.memory: "1536Mi"
    pods: "10"
    persistentvolumeclaims: "3"
