apiVersion: v1
kind: Secret
metadata:
  name: store-secret
type: Opaque
data:
  db-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  admin-password: {{ .Values.wordpress.adminPassword | b64enc | quote }}