apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.wordpress.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.wordpress.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.wordpress.readinessProbe | nindent 12 }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"  # Only for dev/demo; use secrets in prod!
            - name: WORDPRESS_DATABASE_HOST
              value: mysql
            - name: WORDPRESS_DATABASE_USER
              value: {{ .Values.mysql.auth.username }}
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: db-password
            - name: WORDPRESS_DATABASE_NAME
              value: {{ .Values.mysql.auth.database }}