apiVersion: v1
kind: LimitRange
metadata:
  name: store-limit-range
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    type: Container
