apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-provisioner-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: store-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: ["", "apps", "networking.k8s.io", "batch"]
    resources: ["deployments", "statefulsets", "services", "secrets", "configmaps", "persistentvolumeclaims", "ingresses", "jobs"]
    verbs: ["create", "get", "list", "delete", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: store-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: store-provisioner-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: store-provisioner-role
  apiGroup: rbac.authorization.k8s.io
