global:
  environment: production
  ingressDomainSuffix: "example.com"

backend:
  replicaCount: 2
  image:
    repository: ghcr.io/yourusername/store-provisioner-backend
    pullPolicy: Always
    tag: "stable"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
